### PR TITLE
ENH: add plots using ArviZ

### PR DESCRIPTION
**Pull request by eigenfoo**
https://github.com/pymc-devs/pymc3/pull/3338 lays out an easy plotting framework: depend on ArviZ for everything!

I've opted to retain the old PyMC3 names for the plots, even though they disagree with ArviZ's naming.

### CODE REVIEW

**Comment by ColCarroll** [comment]
Could be a top level `plot.py` with just 

```python
__all__ = az.plots.__all__
```

**Comment by eigenfoo** [comment]
If I'm not mistaken, @canyon289 and @fonnesbeck were in favor of keeping the old API. I'm happy to go either way, but we should probably discuss that.

**Comment by twiecki** [comment]
@eigenfoo That was about distributions but certainly the argument can be extended to other parts of the API. I don't think we should do it for plotting because the way pymc3 currently does it is more or less deprecated (only kept for backwards compat, otherwise we'd drop it). So I think this is an opportune time to move away from that here.

What do others think?

**Comment by canyon289** [comment]
I'm in agreement with Thomas here.

There is value in keeping existing PyMC3 notebooks and code running as is, especially since its a library that's in maintenance mode with an active deprecation plan.

I actually don't think we should include plotting at all in PyMC4 and leave it totally to ArviZ to maintain integration. This way there is only one obvious way to do things for PyMC4 plotting. 

Otherwise we'll end up with the an api where `pm.traceplot` and `az.plot_trace` return the exact same result

**Comment by twiecki** [comment]
Seems like we have a consensus, thanks everyone, especially @eigenfoo.

**Comment by canyon289** [comment]
> Just referencing [#58 (comment)](https://github.com/pymc-devs/pymc4/issues/58#issuecomment-456075780) and [#58 (comment)](https://github.com/pymc-devs/pymc4/issues/58#issuecomment-456108539)

I perhaps should add one more comment for some more clarity. I think maintaining  consistency with models is generally a good idea. PyMC3, (like Stan, emcee, Pyro), is a PPL and the model is the core sell of the library. I personally like PyMC3's syntax, so admittedly this is personal preference.

In contrast plotting is not, I personally don't see a compelling reason why PyMC4 should have an alternative syntax from any of the libraries. Especially when putting my ArviZ hat on the goal is to unify plotting across Bayesian libraries.

This discussion is a good one and I'm glad we're having it. Thanks for making things concrete @eigenfoo

**Pull request closed without merging**
