### PR TITLE
Add mixture/normal_mixture

### PR DESCRIPTION
**Pull request by rrkarim**
#197
I wasn't able to run sampling with xla enabled, so the tests are pretty trivial for now since the sampling with nuts takes forever to give some results without xla.

I will tackle (but maybe somebody can help me) the problem so flagging as in progress.

[UPD] my fault, tfp versioning problem, in master the bug was fixed recently.

### CODE REVIEW

**Comment by ColCarroll** [comment]
I think also you also need to add a line in `distributions/__init__.py`:

```python
from .mixture import *
```

the tests look quite good, though, thank you!

**Comment by rrkarim** [comment]
Concern about the naming of transforms, if somebody is gonna use `pm.transforms.Invert(pm.transforms.Transform(...))` it is not gonna work with executor, since it can detect its `scoped_name`. I've added name to `pm.tranforms.Invert` but now executor doesn't see full scoped name.

**Comment by rrkarim** [comment]
It seems like the PR for tensorflow fix was pulled back because of forward compatibility. The tests shouldn't pass.

**Comment by twiecki** [comment]
Seems like tests fail.

**Comment by rrkarim** [comment]
> Seems like tests fail.

It is a tf side issue, tensorflow/tensorflow/issues/35099.

**Comment by junpenglao** [comment]
I pinged the thread to hopefully get some help.

**Comment by rrkarim** [comment]
@junpenglao can we ping the thread again? I wasn't able to get the response.

**Comment by kyleabeauchamp** [comment]
I pinged the TF thread as I tried to do some modeling in pymc4 and also hit the same bug.

**Comment by rrkarim** [comment]
@junpenglao since the tests are not that great for now, can I just mark tests with `batch_ndim=0` to `xfail`? Then hopefully change it back once the issue solved on the tf side.

**Pull request closed without merging**
