### PR TITLE
TST: Added the rugby model as a test case to the pymc4 tests

### PR DESCRIPTION
**Pull request by springcoil**
From the work at the summit.

I've written an example here and done a few sanity checks.

### CODE REVIEW

**Comment by springcoil** [comment]
Some remarks, this is a stop gap before we get pm.Sample to work correctly.

There's some errors in the model specification. This will be fixed - cc @canyon289

**Comment by springcoil** [comment]
@twiecki Do you think this needs to goto example models? Too large a model?

**Comment by twiecki** [comment]
Yeah, maybe turn this into a NB and place it into the notebooks directory.

**Comment by ferrine** [comment]
I will catch up this test case and port it taking in account new desing

**Comment by ferrine** [comment]
BTW, is it actually a test case?

**Comment by ericmjl** [comment]
@ferrine we discussed at the summit that having some simple examples placed in the test suite can be useful as an integration test, in case we make API changes.

**Comment by canyon289** [comment]
@springcoil Did you want to update this to the new syntax or can we close? Just doing house cleaning

**Comment by springcoil** [comment]
I've not got the time sadly.

**Comment by ericmjl** [comment]
Closing this PR, as @ColCarroll has made the notebook.

**Pull request closed without merging**
