### PR TITLE
DOC: add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by eigenfoo**

### CODE REVIEW

**Comment by canyon289** [comment]
For some reason certain lines don't seem to be rendering in the PR but they look correct

image

Otherwise LGTM

**Comment by eigenfoo** [comment]
This looks like a fix: https://stackoverflow.com/a/16426829

**Comment by eigenfoo** [comment]
Ready to merge!

**Comment by ericmjl** [comment]
Merging!

**Pull request merged**
