### PR TITLE
ENH: add all covariance functions for gp from PyMC3

### PR DESCRIPTION
**Pull request by tirthasheshpatel**
Covariance functions added:
- [x] `RatQuad`
- [x] `Exponential`
- [x] `Matern52`
- [x] `Matern32`
- [x] `Matern12`
- [x] `Linear`
- [x] `Polynomial`
- [x] `Cosine`
- [x] `Periodic`
- [x] `Gibbs`
- [x] `WarpedInput`
- [x] ~`Coregion`~
- [x] `ScaledCov`
- [x] ~`Kron`~

Tests added:
- [x] `RatQuad`
- [x] `Exponential`
- [x] `Matern52`
- [x] `Matern32`
- [x] `Matern12`
- [x] `Linear`
- [x] `Polynomial`
- [x] `Cosine`
- [x] `Periodic`
- [x] `Gibbs`
- [x] `WarpedInput`
- [x] ~`Coregion`~
- [x] `ScaledCov`
- [x] ~`Kron`~

Docs added:
- [x] `RatQuad`
- [x] `Exponential`
- [x] `Matern52`
- [x] `Matern32`
- [x] `Matern12`
- [x] `Linear`
- [x] `Polynomial`
- [x] `Cosine`
- [x] `Periodic`
- [x] `Gibbs`
- [x] `WarpedInput`
- [x] ~`Coregion`~
- [x] `ScaledCov`
- [x] ~`Kron`~

Other Tasks:
- [x] Add Notebook for mean and covariance functions.
- [x] Fix docs such that the `pydocstyle` lint pass.

Inconsistencies to be addressed as pointed out by @bwengals and @AlexAndorra :
- [x] Finer grid for x values
- [x] Change some parameters to make heat plots look better.

### CODE REVIEW

**Comment by tirthasheshpatel** [comment]
As tensorflow is not allow slicing tensors with lists and tensors, we will require a workaround for `Coregion` kernel. I think it is possible using `tf.gather` but it will be super slow for large tensors as it creates a copy instead of view... Is there a better way to do this??

**Comment by tirthasheshpatel** [comment]
I have added a basic notebook explaining the usage of `Covariance` functions API. Does it look good or should I add some other section? I am currently following the following format:

1. Explain the kernel function
2. Evaluate it over multiple values or different parameters.
3. Show the covariance matrix.

**Comment by bwengals** [comment]
Coregion and Kron require separate GP model implementations to do properly.  I think it makes sense to not include them in this PR.

**Comment by bwengals** [comment]
Looks really amazing by the way, especially with the batch dimension included!

**Comment by tirthasheshpatel** [comment]
Sure @AlexAndorra. Am working on the notebooks. Will ask for a review when ready

**Comment by tirthasheshpatel** [comment]
I think I have completed all the tasks for this PR. @AlexAndorra can you please review the notebook? Any other comments @fonnesbeck @aloctavodia

**Comment by AlexAndorra** [comment]
Thanks @tirthasheshpatel ! I won't have time today but I'll review this week 😉

**Comment by tirthasheshpatel** [comment]
<p>Arviz style is messing up the Covariance matrix heatplots (it tries to draw a grid on it). Is there a way to disable that behaviour in some particular plots?</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc4/pull/285/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tirthasheshpatel** [comment]
<p>I will have to explain ARD for that. As of now, ARD isn't functional and so I have kept it false everywhere. I will add ARD this or next week and update the notebooks accordingly...</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc4/pull/285/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tirthasheshpatel** [comment]
<p>The plot explains pretty clearly how samples look like. As the samples tensor is very large, tensorflow will truncate them making them very difficult to interpret. Do you mean something else by "showing"? Maybe I misunderstood.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc4/pull/285/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tirthasheshpatel** [comment]
<p>nice idea! Will take some time but I will do that for all the kernels.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc4/pull/285/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tirthasheshpatel** [comment]
<p>Thanks!</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc4/pull/285/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tirthasheshpatel** [comment]
Thank you for the thorough analysis through the notebook.

**Comment by AlexAndorra** [comment]
<p>Ah weird, I've never encountered such problem. Let me come back to you about this ;) </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc4/pull/285/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Ah yeah ok, sounds good :)</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc4/pull/285/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>No I think you understood very well :) I usually like to have a small peak at the raw data before doing anything with them -- even a truncated view usually helps me get a conceptual understanding. But that's a personal preference and may not be appropriate for these examples, so I'll let you decide whether it's useful ;)</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc4/pull/285/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Actually, can you post a screenshot of the problem please? We haven't really encountered this on the ArviZ side. My prior is that you should be able to override the style once you have the figure or axis object -- especially as the heatmaps are done directly with MPL, so everything should be customizable</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc4/pull/285/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tirthasheshpatel** [comment]
Here's the screenshot @AlexAndorra 
arviz_grid_problem

**Comment by tirthasheshpatel** [comment]
<p>Added a nicer explanation!</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc4/pull/285/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tirthasheshpatel** [comment]
<p>I wonder if we should explain broadcasting here. It is an array operation and explained well on some stack-overflow forums and numpy docs. Would a link to that work?</p><p> </p><p>And yes, I will add a better explanation for the <code>feature_ndims</code>  parameter</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc4/pull/285/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
@ColCarroll and @aloctavodia, here is the screenshot with the grid on heatmap I told you about ☝️ 
PS: I kinda like it better with the grid 😅

**Comment by tirthasheshpatel** [comment]
Also, `plt.grid("off")` doesn't work (I don't know if I should expect it to though). Probably this is an issue in the style config file...

**Comment by AlexAndorra** [comment]
<p>Thanks!</p><p>My rule when writing NBs is usually that explicit is better than implicit, so just a 2-3-word of broadcasting would do IMO -- with a link to SO or Numpy docs as you said, that'd be perfect ;)</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc4/pull/285/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
Phew, just finished reviewing the last third of the NB @tirthasheshpatel -- this is quite a NB and really impressive work!
You will find my comments below. Ping me once you've done all the changes and I'll review those as soon as I can 😉 
And of course, tell me if you have any questions!

**Comment by AlexAndorra** [comment]
<p>Regarding this, <code>plt.grid</code> is only for the latest ax, so you should deal with the <em>axes</em> instead of the whole figure. That way, you should be able to plot the heatmap, obtain the axes and then disable the grid for each one of them. </p><p>Something like <code>fig, ax = plt.subplots(1, 2, figsize=(12, 5), constrained_layout=True)</code> could put you on the right track.</p><p>Is that clearer?</p><p> </p><p> </p><p> </p><p> </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc4/pull/285/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tirthasheshpatel** [comment]
<p>Oh sorry! Actually the length scales and amplitudes must be the same. I will have to change the code.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc4/pull/285/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tirthasheshpatel** [comment]
Tried to address as many issues with the notebook as I can. Looks very good now. Thanks, @AlexAndorra.

**Comment by tirthasheshpatel** [comment]
I think build failures are unrelated.

**Comment by tirthasheshpatel** [comment]
everything good to go now? @fonnesbeck @AlexAndorra @aloctavodia

**Comment by bwengals** [comment]
Nice work @tirthasheshpatel!  Left some comments, biggest thing is I think a finer x grid would make a lot of the covariance matrix and sample plots look a lot better.  And also showing more than one sample per parameter setting, maybe 3 panels?  One per parameter setting?

**Comment by tirthasheshpatel** [comment]
<p>It is $\mathcal{O}(n)$ is a sense that that it takes linear time to compute the covariance between a vector of points. I will make that clearer in the description.</p><p> </p><p>Its taken from Tensorflow Probability and it does that in a little more efficient way.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc4/pull/285/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tirthasheshpatel** [comment]
<p>Oh, right! I will then just alias the Matern12 kernel and mention it in the Matern 1/2 section of the notebook.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc4/pull/285/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tirthasheshpatel** [comment]
<p>This is a very helpful review @bwengals! Thanks for taking the time to go through the notebook.</p>

**Comment by tirthasheshpatel** [comment]
<p>I just noticed that Exponential kernel has <code>2l^2</code>  in the denominator while matern just  has <code>l</code> . Does this make difference during inference? If it does, then it should be implemented seperately. What do you say, @bwengals?</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc4/pull/285/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tirthasheshpatel** [comment]
I have added finer grids, 3 panel plots, and addressed nitpicks. How does it look now @bwengals ?

**Comment by bwengals** [comment]
<p>wow! does it really?  I can't seem to find it in their docs (I'm pretty unfamiliar with tf probability, trying to learn more about it lately).  Where does it say?</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc4/pull/285/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by bwengals** [comment]
<p>No.. they're the same, just a different interpretation of the lengthscale because of the scaling, so won't make a diff during inference.  </p><p> </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc4/pull/285/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tirthasheshpatel** [comment]
<p>It is working right. It is just a luck with the random seed. I will change it and commit the plots again...</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc4/pull/285/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tirthasheshpatel** [comment]
<p>Side by side panels will look very compact and i guess the y scale will also get overly streched.  But i will definitely try it out and send a screenshot of the plots. I don't know why reviewnb makes the plots look lot bigger than they are. They look pretty normal on github, jupyter notebook and colab.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc4/pull/285/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tirthasheshpatel** [comment]
<p>Tried a lot of values of different parameters for this one. But the diagonal values always dominate the non diagonal ones. Will try more. What do you say about using a simpler scaling function?</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc4/pull/285/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tirthasheshpatel** [comment]
Sorry, I forgot to update the covariance matrices. Do they look good now? Thanks again for the detailed review @bwengals!

**Comment by tirthasheshpatel** [comment]
@bwengals About the exponential kernel, can I do that in a follow up PR? This has grown quite and bit and it will be easier to review and comment in some other PR.

**Comment by tirthasheshpatel** [comment]
<p>Sorry, I am not able to find it. Somehow this was stuck in my mind. BTW, where are we inverting the kernel matrix during its evaluation? From the implementation in TFP, it seems that this kernel takes $\mathcal{O}(nf)$ (where $f$ are total feature dimensions) to evaluate a vector of covariance and $\mathcal{O}(nf^2)$ time (due to outer product of vectors) to compute the covariance matrix. Does it sound correct now?</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc4/pull/285/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tirthasheshpatel** [comment]
<p>I will update the docs accordingly...</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc4/pull/285/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tirthasheshpatel** [comment]
<p>Oh, ok. I got it now @bwengals. Would it be better to address this in a follow up pr?</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc4/pull/285/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tirthasheshpatel** [comment]
<p>on it.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc4/pull/285/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by bwengals** [comment]
<p>Ahhhhh I see what you're saying, the complexity is just for kernel evaluation, not for the GP as a whole. That's what I thought you meant in the docs.  The solves and matrix multiplications to calculate the posterior mean and covariance are usually the big slowdown, not the kernel calculation.</p><p> </p><p>If one wanted to do GP with linear kernel (no kernel composition or anything else), they would be better off doing the equivalent linear regression model computationally</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc4/pull/285/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tirthasheshpatel** [comment]
<blockquote>x1, x2 = np.meshgrid(np.linspace(-1, 1, 30), np.linspace(-1, 1, 3))?</blockquote><p> </p><p>Tried it out and seems like this is cleaner than showing the matrix used to generate samples!</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc4/pull/285/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tirthasheshpatel** [comment]
Updated everything according to the reviews. How does everything look now @bwengals?

**Comment by bwengals** [comment]
Ok @tirthasheshpatel 2 more little ones!  Thanks for being patient...

**Comment by tirthasheshpatel** [comment]
Thanks for so many helpful reviews @bwengals! I did a little change to the `WarpedInput` kernel but the heat plot is still a little difficult to read. Does it look good to you?

**Comment by tirthasheshpatel** [comment]
Thanks for all these amazing reviews @bwengals! This was fun to do! Any other thoughts though?

**Comment by bwengals** [comment]
Well I think it looks great, LGTM.

**Comment by tirthasheshpatel** [comment]
Requesting @fonnesbeck to merge!

**Comment by fonnesbeck** [comment]
Great work, as always!

**Pull request merged**
