### PR TITLE
Create skeleton, set up CI

### PR DESCRIPTION
**Pull request by ColCarroll**
This adds a bunch of boilerplate for a new project:

- A folder for the main project, with `__version__` in the `__init__.py` 
- A folder for tests.  Run tests with `pytest -xv tests/ --cov=pymc4/`
- Adds linting. Run linter with `pylint pymc4`
- Adds CI (activated [on travis](https://travis-ci.org/pymc-devs/pymc4))
- Adds coverage (activated [on coveralls](https://coveralls.io/github/pymc-devs/pymc4))
- Adds `setup.py` (and travis uses it to install the project, so it should have to work)

### CODE REVIEW

**Comment by sharanry** [comment]
@ColCarroll Hey, can this be merged? I can start writing tests then.

**Comment by ColCarroll** [comment]
Yep, I think it is ready to go!

**Comment by sharanry** [comment]
@ColCarroll I do not have permissions to merge.

**Comment by fonnesbeck** [comment]
@sharanry you should have received an invitation by email. Please check.

**Comment by sharanry** [comment]
@fonnesbeck My bad, was burried in the inbox.

**Pull request merged**
