### PR TITLE
WIP _model.py documentation

### PR DESCRIPTION
**Pull request by ericmjl**
Team, this is my first attempt at documenting `_model.py`. 

@aseyboldt, @canyon289 says there's a lot of your brilliance embedded in this `.py` module. I'd love to hear from you where my ignorance shows up!

### CODE REVIEW

**Comment by eigenfoo** [comment]
Thanks for this! This PR looks like a learning experience for a lot of us 😄 

FYI, the lint is failing. When the PR is ready, you just need to run `black -l 100 --py36 _model.py`.

**Comment by ericmjl** [comment]
@eigenfoo I'm not sure what's the best path forward - should we get others to review the docstrings for accuracy first, or merge first? I'm leaning towards the former, to get things done right.

**Comment by eigenfoo** [comment]
I agree - probably Adrian and Colin should weigh in, since this is their work.

**Comment by eigenfoo** [comment]
Closed in favor of #56

**Pull request closed without merging**
