### PR TITLE
Fix HMC branch

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
1.  This fixes the linter warning/error on travis that says "--py36 is deprecated and will be removed in a future version. Use --target-version py36 instead."
2.  Also fix use of un-imported `DiscreteRV` that was causing UndefinedVariable exception.

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
Note: this PR is pointed into @twiecki 's HMC branch (which isn't HMC, but rather tensorflow2.0 fixes).

**Comment by kyleabeauchamp** [comment]
Test failure is unrelated and likely lingering issues in the target PR branch.

**Comment by canyon289** [comment]
@kyleabeauchamp 
Can you rebase on that branch, or master once its merged, to get a passing CI for this one?

Thank you for the contributions!
https://github.com/pymc-devs/pymc4/pull/92

**Comment by kyleabeauchamp** [comment]
I think this is already based on that branch, in that I checked it out, created a new branch, and pointed the PR into it...

**Comment by kyleabeauchamp** [comment]
I don't think CI passing is going to happen immediately because that branch likely has other issues.  

I could pull out the black config changes as a separate PR into master as well if we like.

**Comment by twiecki** [comment]
You can rebase and point this to master now.

**Pull request closed without merging**
