### PR TITLE
Add baseball example

### LINKED ISSUE #189: Port two more examples
I have examples ready on 
- [https://docs.pymc.io/notebooks/hierarchical_partial_pooling.html](hierarchical partial pooling), and
- [https://docs.pymc.io/notebooks/rugby_analytics.html](rugby analytics)

just wanted to mark that these are incoming.

### PR DESCRIPTION
**Pull request by ColCarroll**
Sporty day!

The baseball example was actually pretty easy to get running. There is no exposition, and everything just... worked. We could add a new issue to expand it into a case study, but I think it is useful as a reference while we keep building this out.

This fixes #189

### CODE REVIEW

**Comment by junpenglao** [comment]
Maybe a bit more docs and explanations like the other PR?

**Comment by fonnesbeck** [comment]
@ColCarroll if you want to go ahead and commit it, I can add supporting text over the weekend.

**Comment by ericmjl** [comment]
Hitting the big green button!

**Comment by fonnesbeck** [comment]
BTW, the plotting cell fails for me:

```python
ValueError                                Traceback (most recent call last)
 in 
      1 player_names = data.apply(lambda x: x.FirstName + ' ' + x.LastName, axis=1)
----> 2 _, ax = az.plot_forest(trace, var_names='baseball_model/thetas', combined=True)
      3 ax[0].set_yticklabels(player_names.tolist()[-1::-1]);

ValueError: not enough values to unpack (expected 2, got 1)
```

This is with Arviz 0.6.0. If this is not new enough, we will have to change the requirements.txt minimum version, since this is how it was installed on my machine.

**Pull request merged**
